from __future__ import annotations

SECURITY_PROTOCOLS = frozenset({"PLAINTEXT", "SSL", "SASL_PLAINTEXT", "SASL_SSL"})
SASL_PROTOCOLS = frozenset({"SASL_PLAINTEXT", "SASL_SSL"})
SSL_PROTOCOLS = frozenset({"SSL", "SASL_SSL"})
PASSWORD_SASL_MECHANISMS = frozenset({"PLAIN", "SCRAM-SHA-256", "SCRAM-SHA-512"})
OAUTH_SASL_MECHANISMS = frozenset({"OAUTHBEARER"})
KERBEROS_SASL_MECHANISMS = frozenset({"GSSAPI"})
SASL_MECHANISMS = PASSWORD_SASL_MECHANISMS | OAUTH_SASL_MECHANISMS | KERBEROS_SASL_MECHANISMS
SCHEMA_REGISTRY_TRANSPORTS = frozenset({"stdlib", "pooled"})


__all__ = [
    "KERBEROS_SASL_MECHANISMS",
    "OAUTH_SASL_MECHANISMS",
    "PASSWORD_SASL_MECHANISMS",
    "SASL_MECHANISMS",
    "SASL_PROTOCOLS",
    "SCHEMA_REGISTRY_TRANSPORTS",
    "SECURITY_PROTOCOLS",
    "SSL_PROTOCOLS",
]
