port 26379
bind 0.0.0.0
protected-mode no
sentinel resolve-hostnames yes
sentinel announce-hostnames yes
sentinel monitor mymaster redis-primary 6379 1
sentinel down-after-milliseconds mymaster 2000
sentinel failover-timeout mymaster 5000
sentinel parallel-syncs mymaster 1
